name: Solar system workflow

on:
    workflow_dispatch:
    push:
        branches:
            - main
            - 'feature/*'

# env:
#     MONGO_URL: 'mongodb+srv://supercluster.d83jj.mongodb.net/superData'
#     MONGO_USERNAME: ${{ vars.MONGO_USERNAME }}
#     MONGO_PASSWORD: ${{ secrets.MONGO_PASSWORD }}

env:
  MONGO_URI: 'mongodb+srv://supercluster.d83jj.mongodb.net/superData'
  MONGO_USERNAME: ${{ vars.MONGO_USERNAME }}
  MONGO_PASSWORD: ${{ secrets.MONGO_PASSWORD }}

jobs:
    unit-testing:
        name: Unit testing
        # strategy:
        #     matrix:
        #         nodejs_version: [18, 19, 20]
        #         operating_system: [ubuntu-latest, macos-latest]
        #         exclude:
        #             - operating_system: macos-latest

        runs-on: ubuntu-latest

        steps:
        - name: Checkout repo
          uses: actions/checkout@v4
        
        - name: Setup NodeJS V - 18
          uses: actions/setup-node@v3
          with:
            node-version: 18

        - name: Cache NPM Dependencies
          uses: actions/cache@v4
          with:
            path: node_modules                                                            # path where dependencies are installed
            key: ${{ runner.os }}-node-modules-${{ hashfiles('package-lock.json') }}      # this validates package-lock.json if there is any change in that file it will clear the cache
        
            
        - name: Install Dependencies
          run: npm install

        - name: Unit testing
          id: nodejs-unit-testing-step
          run: npm test

        - name: Archive Test Result
          if: always()                          # It runs always even the above step is success or failed
          uses: actions/upload-artifact@v4
          with:
            name: Mocha-Test-Result
            path: test-results.xml

    code-coverage:
        name: Code Coverage
        runs-on: ubuntu-latest

        steps:
        - name: Checkout repo
          uses: actions/checkout@v4
        
        - name: Setup NodeJS V - 18
          uses: actions/setup-node@v3
          with:
            node-version: 18

        - name: Cache NPM Dependencies
          uses: actions/cache@v4
          with:
            path: node_modules
            key: ${{ runner.os }}-node-modules-${{ hashfiles('package-lock.json') }}      
        
        - name: Install Dependencies
          run: npm install

        - name: Check Code Coverage
          continue-on-error: true
          run: npm run coverage

        - name: Archive Test Result
          uses: actions/upload-artifact@v4
          with:
            name: Code-Coverage-Result
            path: coverage
            retention-days: 5


