name: Solar system workflow

on:
    workflow_dispatch:
    push:
        branches:
            - main
            - 'feature/*'

# env:
#     MONGO_URL: 'mongodb+srv://supercluster.d83jj.mongodb.net/superData'
#     MONGO_USERNAME: ${{ vars.MONGO_USERNAME }}
#     MONGO_PASSWORD: ${{ secrets.MONGO_PASSWORD }}

env:
  MONGO_URI: 'mongodb+srv://supercluster.d83jj.mongodb.net/superData'
  MONGO_USERNAME: ${{ vars.MONGO_USERNAME }}
  MONGO_PASSWORD: ${{ secrets.MONGO_PASSWORD }}

jobs:
    unit-testing:
        name: Unit testing
        # strategy:
        #     matrix:
        #         nodejs_version: [18, 19, 20]
        #         operating_system: [ubuntu-latest, macos-latest]
        #         exclude:
        #             - operating_system: macos-latest

        runs-on: ubuntu-latest

        steps:
        - name: Checkout repo
          uses: actions/checkout@v4
        
        - name: Setup NodeJS V - 18
          uses: actions/setup-node@v3
          with:
            node-version: 18

        - name: Cache NPM Dependencies
          uses: actions/cache@v4
          with:
            path: node_modules                                                            # path where dependencies are installed
            key: ${{ runner.os }}-node-modules-${{ hashfiles('package-lock.json') }}      # this validates package-lock.json if there is any change in that file it will clear the cache
        

        - name: Install Dependencies
          run: npm install

        - name: Unit testing
          id: nodejs-unit-testing-step
          run: npm test

        - name: Archive Test Result
          if: always()                          # It runs always even the above step is success or failed
          uses: actions/upload-artifact@v4
          with:
            name: Mocha-Test-Result
            path: test-results.xml

    code-coverage:
        name: Code Coverage
        runs-on: ubuntu-latest

        steps:
        - name: Checkout repo
          uses: actions/checkout@v4
        
        - name: Setup NodeJS V - 18
          uses: actions/setup-node@v3
          with:
            node-version: 18

        - name: Cache NPM Dependencies
          uses: actions/cache@v4
          with:
            path: node_modules
            key: ${{ runner.os }}-node-modules-${{ hashfiles('package-lock.json') }}      
        
        - name: Install Dependencies
          run: npm install

        - name: Check Code Coverage
          continue-on-error: true
          run: npm run coverage

        - name: Archive Test Result
          uses: actions/upload-artifact@v4
          with:
            name: Code-Coverage-Result
            path: coverage
            retention-days: 5

    docker-setup:
      name: Continerization
      needs: [unit-testing, code-coverage]              # Only runs if the mentioned blocks are success
      permissions:
          packages: write
      runs-on: ubuntu-latest
      steps:
        - name: Checkout Repo
          uses: actions/checkout@v4

        - name: Dockerhub Login
          uses: docker/login-action@v4
          with:
            username: ${{ vars.DOCKERHUB_USERNAME }}
            password: ${{ secrets.DOCKERHUB_PASSWORD }}

        - name: GitHub Container Registry Login
          uses: docker/login-action@v4
          with:
            registry: ghcr.io                               # points to GitHub Container Registry
            username: ${{ github.repository_owner }}        # Use github owner name as user
            password: ${{ secrets.GITHUB_TOKEN }}           # Generate a temporary token for authentication

        - name: Docker Build
          uses: docker/build-push-action@v4
          with:
            context: .                                  # it will search for dockerfile in root directory
            push: false                                 # if its not set to false this block will build and push the image
            tags: ${{ vars.DOCKERHUB_USERNAME }}/solar-system:${{ github.sha }}      # github.sha uses commit ID

        - name: Docker Image testing
          run: |
            # Step 1: List all available Docker images (to verify image is pulled/built)
            
            docker images

            # Step 2: Run the Docker container in detached mode
            # - Assign a name to the container
            # - Map port 3000 (host -> container)
            # - Pass MongoDB environment variables
            # - Use image tagged with current Git commit SHA
            
            docker run --name solar-system-app -d \
                -p 3000:3000 \
                -e MONGO_URI=$MONGO_URI \
                -e MONGO_USERNAME=$MONGO_USERNAME \
                -e MONGO_PASSWORD=$MONGO_PASSWORD \
                ${{ vars.DOCKERHUB_USERNAME }}/solar-system:${{ github.sha }}
            
            # Step 3: Fetch the container's internal IP address (useful for debugging)
            
            export IP=$(docker inspect -f '{{range .NetworkSettings.Networks}}{{.IPAddress}}{{end}}' solar-system-app )
            echo $IP

            # Step 5: Test application health endpoint
            # - Send request to /live endpoint
            # - Quiet mode (-q), output response (-O -)
            # - grep ensures the response contains "live"
            
            echo Testing Image URL using wget
            wget -q -O - http://127.0.0.1:3000/live | grep live
            
        - name: Multi Container Registry Push
          uses: docker/build-push-action@v4
          with:
            context: .                                  # it will search for dockerfile in root directory
            push: true                                  # if its not set to false this block will build and push the image
            tags: |
                ${{ vars.DOCKERHUB_USERNAME }}/solar-system:${{ github.sha }}
                ghcr.io/${{ github.repository_owner }}/solar-system:${{ github.sha }}
